import Header from './Header/Header';
import TopbarLeft from './Header/TopbarLeft';
import Home from './Home/Home';
import BoxMarket from './Home/BoxMarket';
import TabHome from './Home/TabHome';   
import CoinList from './CoinList/CoinList';
import FaqSection from './Home/FaqSection'; 
import BlogCard from './Blog/BlogCard';
import Footer from './Footer/Footer';       
import SinglePage from './SinglePage/SinglePage';
import Breadcrumbs from './Breadcrumbs/Breadcrumbs';
import BTCConverter from './BTCconverter/BTCConverter';
import CoinInfo from './SinglePage/CoinInfo';
import CustomSwitch from './CustomSwitch/CustomSwitch';
export { Header, TopbarLeft, Home, BoxMarket, TabHome, CoinList, FaqSection, BlogCard, Footer, SinglePage, Breadcrumbs, BTCConverter, CoinInfo, CustomSwitch };